//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Monthly
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Item field required")]
        public string item { get; set; }

        [Required(ErrorMessage = "Money field required")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Money must be numeric")]
        public Nullable<decimal> money { get; set; }
    }
}
